# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b73a2b128df3419b787498ef8022213fc433be518a5b440bd6a2f1b0c66e93b0495e1e4df7081829f41efff4e8685306cace6415fc32c6ecdd223f1c277029dd

test:
  secret_key_base: 4d9d456a41fa23c4cc460b5cb681ae7792b3d3fcc4ffb4889b246f4a9da6cd54edff4236e443a3d6502b2f09bc7f6a966de1235c188aae75a180f33691cc6e38

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
